services:
  redis:
    container_name: redis
    image: redis:8.2-rc1-alpine
    ports:
      - "6379:6379"
    networks:
      - cloud-sell-network

networks:
  cloud-sell-network:
    external: true
    name: cloud-sell-network